### PR TITLE
Variables templating

### PR DESCRIPTION
**Pull request by 3dgiordano**
Hi guys

I am working on a proposal to incorporate the use of variables into selenium, which can also be used with apiritif in the rest of the functionalities in the future.

I show you an example of use

import apiritif

apiritif.variables = {"h": "Hello", "w": "World"}
print(apiritif.apply("${h} ${w}! ${no_match_and_is_ok}"))

I used to have a version with the same approach of generating the variable "vars" in a global way, but when trying to go to the next level, manipulating them generated a code too verbose, and I opted for this approach that allows to hide complexity and generate simpler code.

If the proposal is accepted, I will be able to continue with the improvements that I intend to propose to the generation of selenium with nose using the new apiritif, and we could incorporate the improvements to the apiritif code generator.

### CODE REVIEW

**Comment by dmand** [comment]
Hi,

Thanks for raising the question and for providing an implementation.

The issue i see with this implementation is that variables will be shared between many threads (assuming it's executed in load-testing mode, of course). It happens because in a single Python process `apiritif` module will be imported only once, and then imported module will be shared between multiple threads. Handling it the right way (by adding a variable storage per thread) will add a lot of complexity. And that's why we've decided to implement it on a codegen side.

Can you explain how generating reasonably concise code that manipulates variables will be hard? An example or a use case would be nice.

**Comment by 3dgiordano** [comment]
True! I forgot to take into account the multithread mode, that I can easily solve.

Mainly the code reduction proposal is on how to use the Template and the "vars" variables of how they are generated today.
Actually, It is necessary to create at the level of the script the classes that implement the template system and that they have previously associated to which vector to use so as not to be passing to each operation the dictionary of variables.
Having the template system at apiritif level and creating a class that contains the variables and the template system in one is possible to generate a cleaner source code.

Like this (pseudocode)

import apiritif
vars = apiritif.Variables({"h": "Hello", "w": "World"})
print(vars.apply("${h} ${w}! ${no_match_and_is_ok}"))

In the next update of PR I will show you how it would be (thread safe like the previous example).

Give me a few hours and I will send you an example in an update of this PR.

**Comment by 3dgiordano** [comment]
Hi @dmand !
What do you think about the previous change I made to the PR?
In the previous post I show how simple it could be.

About the term "hard" mentioned by you, I did't mention that it was hard, I mentioned that it would have to include classes and template code in the test code (test_requests.py), so the suggestion of migrating it to apiritif as part of the core, and use it generating a simple code as possible.

Regarding the handling of variables within the aperitif module, it was my mistake to include it.
The proposal mainly related to how to have "template" inside strings in apiritif.

The code that currently has this PR I have been using it on my fork and I will soon release a PR in taurus with 12 new commands around selenium, including the handling of variables with this template support (from variables or from text provided by the user in the yml, like jmeter).

I am already testing this template system in my forked version of apiritif, aligned with the latest version.
But to continue with the PR in Taurus, first I need to know if the code as it is now could be incorporated or not in apiritif, or if I have to go another way (in or out of apiritif).

I look forward to an answer that can guide me on how to proceed.

**Comment by undera** [comment]
David, we have certain ideas that we put into the things we do. One of the ideas is to be obvious for users. When the code uses simple formatting of variables, it is extremely obvious. When the code starts to use some maps that store data and user has to consider this when reading generated source, it becomes less trivial. And our idea of Apiritif code is to not be a framework, rather a library. 

Regarding your Taurus fork and plans to bring large PR, please be ready that we won't agree to all the changes and the way you make these changes. Better approach is maybe first bring in your planned changes as discussion on mailing list, and only then spend time implementing it. Also, having separate smaller PRs helps to review faster and not waste effort.

I appreciate your willingnes to contribute, this is why I'm explaining all these possible friction points. For example, this PR sounds overlapping with what you mention: https://github.com/Blazemeter/taurus/pull/818

**Comment by 3dgiordano** [comment]
Hi @undera 
Thank you for your comments

I agree with apiritif as a library, I am not saying otherwise. If you think the proposal is not right, simply tell me what I should take into consideration to collaborate with ideas with all of you.

I find it very good in what @greyfenrir is working on, maybe what I have done can supplement or collaborate with the work they are doing and we can do something together without generating friction.

Currently there is no forum or slack for developers and collaborators to taurus (that I know), the current seems more assigned to user support. 
If there is one, maybe it would be good to incorporate it into the development guide.
https://github.com/Blazemeter/taurus/blob/master/site/dat/docs/DeveloperGuide.md
As in other communities, it is necessary to have a place where developers can communicate and collaborate with each other.

Related to the commands, no problem, each change will have its PR and each one its associated documentation and changelog (as in my previous collaborations).
 
Related to the overlap, it's not a problem for me, my job is to create quick prototypes of things not planned or implemented. The ideas that evolve, I have to collaborate to the source (rewrite and create proposals, can be accepted or not, I have it clear and that is beyond of my control)

Please, tell me how I can help, how I can communicate with all devs in a better way to collaborate and not generate friction.

**Comment by undera** [comment]
There is not special place to discuss development of Taurus. Regular project support forum is suitable for that, as well as PR threads.

**Comment by 3dgiordano** [comment]
Perfect, thanks.
I close this pull request. 
The mechanism will be suggested in taurus using another mechanism, not incorporating it into apiritif.

**Pull request closed without merging**
